# -*- coding: utf-8 -*-
"""Analisis de BD de cancer Predicción de variables .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p1bhqnWLLk4Ctlyz9Qu6eR9kwYMojIJz
"""



import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.tree import DecisionTreeClassifier

df=pd.read_csv('diabetes_prediction_dataset.csv', sep=";")
df

x=df.drop('diabetes', axis=1)

matriz_confusion=confusion_matrix(y_test,svm.predict (x_test))
matriz_confusion

arboles=DecisionTreeClassifier()
arboles.fit(x_train, y_train)

accuracy_arbol=accuracy_score(y_test,arboles.predict(x_test))
accuracy_arbol

matriz_confusion_arbol=confusion_matrix(y_test,arboles.predict (x_test)
matriz_confusion_arbol